# Generated by Django 6.0 on 2025-12-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_followus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_heading',
            field=models.TextField(max_length=20),
        ),
    ]
