# Generated by Django 6.0 on 2025-12-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_about_about_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followus',
            name='follow_us_heading',
        ),
    ]
